# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c08d4ab4b0082ab77daaecb9e998b9e60ee475278f26da6c948f37a500531b07db4638b3af2619bd8044581c1aa07c4d4f7da2643ba00c44f48770b199009b0

test:
  secret_key_base: ef3bd5234c518d1b135232682ad93a4b2d5930cdafd273f20910cf4d7bc222fbc25636f2a8330574907106271037bafd29248a05ce78aefdde43417432836889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
